Ushtrime2ProvimGrupi1/Entities/Shkrimet.cs
using System;
using System.Collections.Generic;

#nullable disable

namespace Ushtrime2ProvimGrupi1.Entities
{
    public partial class Shkrimet
    {
        public int Id { get; set; }
        public string Titulli { get; set; }
        public int AutoriId { get; set; }
        public int KategoriaId { get; set; }

        public virtual Autori Autori { get; set; }
        public virtual Kategorium Kategoria { get; set; }
    }
}

Ushtrime2ProvimGrupi1/Controllers/ShkrimetsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Ushtrime2ProvimGrupi1.Entities;

namespace Ushtrime2ProvimGrupi1.Controllers
{
    public class ShkrimetsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ShkrimetsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Shkrimets
        public async Task<IActionResult> Index(string emri)
        {
            if (string.IsNullOrEmpty(emri))
            {
                var appDbContext = _context.Shkrimets.Include(s => s.Autori).Include(s => s.Kategoria);
                return View(await appDbContext.ToListAsync());
            }
            
            var list = await _context.Shkrimets.Include(s => s.Autori).Include(s => s.Kategoria).Where(s => s.Kategoria.Emri == emri).ToListAsync();
            
            return View(list);
        }

        // GET: Shkrimets/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var shkrimet = await _context.Shkrimets
                .Include(s => s.Autori)
                .Include(s => s.Kategoria)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (shkrimet == null)
            {
                return NotFound();
            }

            return View(shkrimet);
        }

        // GET: Shkrimets/Create
        public IActionResult Create()
        {
            ViewData["AutoriId"] = new SelectList(_context.Autoris, "Id", "Emri");
            ViewData["KategoriaId"] = new SelectList(_context.Kategoria, "Id", "Emri");
            return View();
        }

        // POST: Shkrimets/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Titulli,AutoriId,KategoriaId")] Shkrimet shkrimet)
        {
            if (ModelState.IsValid)
            {
                _context.Add(shkrimet);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["AutoriId"] = new SelectList(_context.Autoris, "Id", "Emri", shkrimet.AutoriId);
            ViewData["KategoriaId"] = new SelectList(_context.Kategoria, "Id", "Emri", shkrimet.KategoriaId);
            return View(shkrimet);
        }

        // GET: Shkrimets/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var shkrimet = await _context.Shkrimets.FindAsync(id);
            if (shkrimet == null)
            {
                return NotFound();
            }
            ViewData["AutoriId"] = new SelectList(_context.Autoris, "Id", "Emri", shkrimet.AutoriId);
            ViewData["KategoriaId"] = new SelectList(_context.Kategoria, "Id", "Emri", shkrimet.KategoriaId);
            return View(shkrimet);
        }

        // POST: Shkrimets/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Titulli,AutoriId,KategoriaId")] Shkrimet shkrimet)
        {
            if (id != shkrimet.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(shkrimet);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ShkrimetExists(shkrimet.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["AutoriId"] = new SelectList(_context.Autoris, "Id", "Emri", shkrimet.AutoriId);
            ViewData["KategoriaId"] = new SelectList(_context.Kategoria, "Id", "Emri", shkrimet.KategoriaId);
            return View(shkrimet);
        }

        // GET: Shkrimets/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var shkrimet = await _context.Shkrimets
                .Include(s => s.Autori)
                .Include(s => s.Kategoria)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (shkrimet == null)
            {
                return NotFound();
            }

            return View(shkrimet);
        }

        // POST: Shkrimets/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var shkrimet = await _context.Shkrimets.FindAsync(id);
            _context.Shkrimets.Remove(shkrimet);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ShkrimetExists(int id)
        {
            return _context.Shkrimets.Any(e => e.Id == id);
        }
    }
}

Ushtrime2ProvimGrupi1/Views/Shkrimets/Create.cshtml
@model Ushtrime2ProvimGrupi1.Entities.Shkrimet

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Shkrimet</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Titulli" class="control-label"></label>
                <input asp-for="Titulli" class="form-control" />
                <span asp-validation-for="Titulli" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AutoriId" class="control-label"></label>
                <select asp-for="AutoriId" class ="form-control" asp-items="ViewBag.AutoriId"></select>
            </div>
            <div class="form-group">
                <label asp-for="KategoriaId" class="control-label"></label>
                <select asp-for="KategoriaId" class ="form-control" asp-items="ViewBag.KategoriaId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Ushtrime2ProvimGrupi1/Views/Shkrimets/Delete.cshtml
@model Ushtrime2ProvimGrupi1.Entities.Shkrimet

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Shkrimet</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Titulli)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Titulli)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Autori)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Autori.Emri)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Kategoria)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Kategoria.Emri)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Ushtrime2ProvimGrupi1/Views/Shkrimets/Details.cshtml
@model Ushtrime2ProvimGrupi1.Entities.Shkrimet

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Shkrimet</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Titulli)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Titulli)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Autori)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Autori.Emri)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Kategoria)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Kategoria.Emri)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Ushtrime2ProvimGrupi1/Views/Shkrimets/Edit.cshtml
@model Ushtrime2ProvimGrupi1.Entities.Shkrimet

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Shkrimet</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Titulli" class="control-label"></label>
                <input asp-for="Titulli" class="form-control" />
                <span asp-validation-for="Titulli" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AutoriId" class="control-label"></label>
                <select asp-for="AutoriId" class="form-control" asp-items="ViewBag.AutoriId"></select>
                <span asp-validation-for="AutoriId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="KategoriaId" class="control-label"></label>
                <select asp-for="KategoriaId" class="form-control" asp-items="ViewBag.KategoriaId"></select>
                <span asp-validation-for="KategoriaId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Ushtrime2ProvimGrupi1/Views/Shkrimets/Index.cshtml
@model IEnumerable<Ushtrime2ProvimGrupi1.Entities.Shkrimet>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>
<form asp-action="Index" asp-controller="Shkrimets" method="get">
    <label>Emri i kategorise</label>
    <input type="text" name="emri" />

    <input type="submit" value="Kerko" />
</form>
<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Titulli)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Autori)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Kategoria)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Titulli)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Autori.Emri)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Kategoria.Emri)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>